workflows:
  biomark-android:
    name: BioMark Android Build
    instance_type: linux
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - google_play
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_OUTPUT_PATH: android/app/build/outputs/apk/release
        PACKAGE_NAME: com.biomarking.app.biomark
      java: 11
      node: 16.14.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'BM-*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Installing Dependencies
        script: |
          yarn install --ignore-optional
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up keystore
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEYSTORE_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Build Android release
        script: |
          # Set environment variable so it can be used to increment build number in android/app/build.gradle
          # Note that tracks can be specified when retrieving latest build number from Google Play, for example:
          # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))
          export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          cd android 
          chmod +x gradlew && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - jem.zubiri@biomarking.com
      slack:
        channel: '#testing-team'
        notify:
          success: true
      scripts:
        - echo 'Post-publish script'

  biomark-android-prod:
    name: BioMark Android Build Production
    instance_type: linux
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - google_play
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
      java: 11
      node: 16.14.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Installing Dependencies
        script: |
          yarn install --ignore-optional
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up keystore
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEYSTORE_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Build Android release
        script: |
          # Set environment variable so it can be used to increment build number in android/app/build.gradle
          # Note that tracks can be specified when retrieving latest build number from Google Play, for example:
          # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))
          export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
      email:
        recipients:
          - jem.zubiri@biomarking.com
      scripts:
        - echo 'Post-publish script'

  biomark-ios:
    name: BioMark iOS Build
    instance_type: mac_mini
    max_build_duration: 120
    environment:
      groups:
        - app_store_credentials
        - certificate_credentials
      vars:
        XCODE_WORKSPACE: './ios/BioMark.xcworkspace'
        XCODE_SCHEME: 'BioMark'
        BUNDLE_ID: 'com.biomark.patientios'
      node: 16.14.2
      xcode: 13
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'BM-*'
        - pattern: 'master'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Installing Dependencies
        script: |
          yarn install --ignore-optional
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Cocoapods installation
        script: |
          cd ios && pod install
      - name: Set up keychain to be used for code signing
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - jem.zubiri@biomarking.com
        notify:
          success: true
